### ISSUE TITLE
plugins build fail

### ISSUE THREAD

**Issue by Selur** [Selur/hybrid-vapoursynth-addon#11]
Currently failing:
* assrender (works now)
* bestsource
* ffms2
* imwri (broken by patch https://github.com/Selur/hybrid-vapoursynth-addon/pull/10)  (fixed)
* vslsmsashsource

problem is probably the need for newer libav.

**Comment by Selur** [comment]
fixed imwri

**Comment by sosie-js** [comment]
Personally, I have built the plugins using ffmpeg_7.0.1-0ubuntu1~22.04.sav0.1_amd64 sources

For that I added savoury1-ubuntu-ffmpeg7-jammy.list in /etc/apt/sources.list.d
deb https://ppa.launchpadcontent.net/savoury1/ffmpeg7/ubuntu/ jammy main
deb-src https://ppa.launchpadcontent.net/savoury1/ffmpeg7/ubuntu/ jammy main

then
```
sudo apt udate
cd /usr/src
apt source -b ffmpeg
and so on..
```

**Comment by Selur** [comment]
Not really a solution, complicating the installation even further with manual steps needed.
(btw. assrender is render is working again)
Maybe I'll change the min requirement to Ubuntu 24.04 in the future, that probably fixes the problem.

**Comment by Selur** [comment]
on Ubuntu 24.04 bestsource&co work, but there akarin and f3kdb fail :(

**Comment by Selur** [comment]
Since current scripts work fine on 22.04 now I close this.
Will look into 24.04 building separately, since 22.04 is supported till April 2027, no hurry there.
