### ISSUE TITLE
Debuging plugins that fails to build

### ISSUE THREAD

**Issue by sosie-js** [Selur/hybrid-vapoursynth-addon#7]
Hello Selur,

Big thanks for your install scripts ! 
I suggest you these improvements:
1)not to remove the build directory and logs on failure
   'plugin x fails' is a bit borring 

 then looking in build/log/plugin to have a clue of the problem
To fix it I commented in build-plugins.sh thus 
```
 #rm -rf build build.sh # remove build folder and build script
```
and
```
#cd $build_pwd/..
#rm -rf build
```
2)indicate you can install a particular plugin by overriding plugins in build-plugins.sh
3) indicate also in your doc VSPREFIX can be changed in config.txt to by example /usr/local instead of /opt
doing this with magick links avoid [PYTHONPATHETIC maze as described here](https://github.com/vapoursynth/vapoursynth/issues/1064#issuecomment-2181126336)
4)Moreover I don't think having runing this as root is *NOT* a good thing..
```sudo ./build-plugins.sh```
use sudo in the install scripts when writings rights are needed not during compilation

**Comment by Selur** [comment]
a. patches are welcome
b. regarding sudo: 
I agree that calling it with `sudo ./build-plugins.sh` is how one should call the script.
sudo is not required during the compilation, but for the apt calls. The script should only use 'sudo' in such cases.
I always call the script with `build-plugins.sh` as my normal user, and then I'm asked for credentials for sudo.
