### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 362227** [Selur/hybrid-vapoursynth-addon#9]
colab.research.google.com - CPU

!git clone https://github.com/Selur/hybrid-vapoursynth-addon
!cd hybrid-vapoursynth-addon && chmod +x build-vapoursynth.sh && bash build-vapoursynth.sh

`
CC	libavcodec/nvenc.o
libavcodec/nvenc.c: In function ‘nvenc_setup_hevc_config’:
libavcodec/nvenc.c:1360:9: error: ‘NV_ENC_CONFIG_HEVC’ {aka ‘struct _NV_ENC_CONFIG_HEVC’} has no member named ‘pixelBitDepthMinus8’
 1360 |     hevc->pixelBitDepthMinus8 = IS_10BIT(ctx->data_pix_fmt) ? 2 : 0;
      |         ^~
libavcodec/nvenc.c: In function ‘nvenc_setup_av1_config’:
libavcodec/nvenc.c:1446:8: error: ‘NV_ENC_CONFIG_AV1’ {aka ‘struct _NV_ENC_CONFIG_AV1’} has no member named ‘inputPixelBitDepthMinus8’
 1446 |     av1->inputPixelBitDepthMinus8 = IS_10BIT(ctx->data_pix_fmt) ? 2 : 0;
      |        ^~
libavcodec/nvenc.c:1447:8: error: ‘NV_ENC_CONFIG_AV1’ {aka ‘struct _NV_ENC_CONFIG_AV1’} has no member named ‘pixelBitDepthMinus8’
 1447 |     av1->pixelBitDepthMinus8 = (IS_10BIT(ctx->data_pix_fmt) || ctx->highbitdepth) ? 2 : 0;
      |        ^~
libavcodec/nvenc.c: In function ‘nvenc_map_buffer_format’:
libavcodec/nvenc.c:1676:16: error: ‘NV_ENC_BUFFER_FORMAT_YV12_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_YV12’?
 1676 |         return NV_ENC_BUFFER_FORMAT_YV12_PL;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                NV_ENC_BUFFER_FORMAT_YV12
libavcodec/nvenc.c:1676:16: note: each undeclared identifier is reported only once for each function it appears in
libavcodec/nvenc.c:1678:16: error: ‘NV_ENC_BUFFER_FORMAT_NV12_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_NV12’?
 1678 |         return NV_ENC_BUFFER_FORMAT_NV12_PL;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                NV_ENC_BUFFER_FORMAT_NV12
CC	libavcodec/nvenc_av1.o
libavcodec/nvenc.c:1684:16: error: ‘NV_ENC_BUFFER_FORMAT_YUV444_PL’ undeclared (first use in this function); did you mean ‘NV_ENC_BUFFER_FORMAT_YUV444’?
 1684 |         return NV_ENC_BUFFER_FORMAT_YUV444_PL;
      |                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                NV_ENC_BUFFER_FORMAT_YUV444
make: *** [ffbuild/common.mak:81: libavcodec/nvenc.o] Error 1
make: *** Waiting for unfinished jobs....

`

**Comment by Selur** [comment]
This addon is written for Ubuntu systems.
`colab.research.google.com - CPU` this probably means no gpu support, so try removing 
line [136](https://github.com/Selur/hybrid-vapoursynth-addon/blob/e8e8744c523eb8a179ed8befe9ae5757bb327f95/build-vapoursynth.sh#L136) to [141](https://github.com/Selur/hybrid-vapoursynth-addon/blob/e8e8744c523eb8a179ed8befe9ae5757bb327f95/build-vapoursynth.sh#L141)
and line [155](https://github.com/Selur/hybrid-vapoursynth-addon/blob/e8e8744c523eb8a179ed8befe9ae5757bb327f95/build-vapoursynth.sh#L155) and [156](https://github.com/Selur/hybrid-vapoursynth-addon/blob/e8e8744c523eb8a179ed8befe9ae5757bb327f95/build-vapoursynth.sh#L156)
